In [3]:
import numpy as np 
import pandas as pd
Data={'Names':['Ramesh','Suresh','Sathish',np.nan],'Age':[np.nan,22,25,27],'City':['Pune','Pune',np.nan,'Hyd']}
df=pd.DataFrame(Data)
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [5]:
missing=df.to_csv('data_missing.csv',index=False)

In [7]:
pd.read_csv('data_missing.csv')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [9]:
Data1={'Names':['Ramesh','Suresh','Sathish',None],
      'Age':[None,22,25,27],
      'City':['Pune','Pune',None,'Hyd']}
df1=pd.DataFrame(Data1)
df1

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  None
3     None  27.0   Hyd

In [11]:
df1.to_csv('data1_missing.csv',index=False)


In [13]:
pd.read_csv('data1_missing.csv')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [15]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [17]:
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [19]:
df.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [21]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fillna**

In [24]:
df.fillna(30)  #fillthe all names also replace with 30 

Names   Age  City
0   Ramesh  30.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0    30
3       30  27.0   Hyd

**What is the difference between np.nan and None**

In [27]:
np.nan+5

nan

In [29]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [31]:
arr1=np.array([1,2,np.nan,3])
arr2=np.array([1,2,None,3])

In [33]:
arr1

array([ 1.,  2., nan,  3.])

In [35]:
arr2

array([1, 2, None, 3], dtype=object)

In [37]:
np.nansum(arr1),np.sum(arr1)

(6.0, nan)

In [39]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan rpresents float type

- None represents Object type

- if data operation related to maths then nan format is better '
'

**Fill the value based on column**

In [43]:
df['Names'].fillna('Manish')


0     Ramesh
1     Suresh
2    Sathish
3     Manish
Name: Names, dtype: object

In [1]:
df

NameError: name 'df' is not defined

**Methods**
  
    - pad

    - bfill

    - ffill

    - backfill

In [48]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [50]:
df.fillna(method='bfill')

Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [52]:
df.fillna(method='ffill')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [54]:
df.fillna(method='backfill')

Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [56]:
df.fillna(method='pad',axis=1) ## differnce 

Names     Age  City
0   Ramesh  Ramesh  Pune
1   Suresh    22.0  Pune
2  Sathish    25.0  25.0
3      NaN    27.0   Hyd

In [58]:
df.fillna(method='pad')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [60]:
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

**Mean-Median-Mode**

In [73]:
age_mean=df['Age'].mean()
print(age_mean)
df['Age'].fillna(age_mean)

24.666666666666668


0    24.666667
1    22.000000
2    25.000000
3    27.000000
Name: Age, dtype: float64

In [ ]:
- idea-1:filling with random value=df.fillname(<random value>)

- idea-2:filling with random value basesd on column =df.fillname(<random value>)

- idea-3:filling with some patterns using a method:df.fillna(method)

- idea-4:filling with m-m-m based on column=df[<col>].fillname(<mean>or<median>or<mode>)

- idea-5:filling with avg value only selected neighbours 

- idea-6:filling with the value based on corelation with onther columns 

In [79]:
city_mode=df['City'].mode()
df['City'].fillna(city_mode)

0    Pune
1    Pune
2     NaN
3     Hyd
Name: City, dtype: object

In [85]:
age_mean   #fixed value

24.666666666666668

In [87]:
city_mode    #series

0    Pune
Name: City, dtype: object

In [89]:
city_mode.values[0]


'Pune'

In [99]:
city_mode.values[0]

'Pune'

- In future sometime if we direct impute mode value we will get  error 

- mode is coming as series 

- mean is coming as fixed value

- so first convert series to fixed value then apply it 

**impute class** 

In [104]:
from sklearn import impute

In [109]:
dir(impute)

['KNNImputer',
 'MissingIndicator',
 'SimpleImputer',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_knn',
 'typing']

**KNN Imputer**



- K-Nearest Neighbours

- where k=hyper parameter which means the user can change 

- Idea:Instead of talking all the samples averages 

- First fix the neighbours number i.e k

- Then find the neighbours using disatance metric 

- Then taking the average of those samples to fill the missing value 


In [119]:
import numpy as np 
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [125]:
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,weights='distance')
imputer.fit_transform(X)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

In [131]:

from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

**Practice Question on the missing_value**

In [52]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [50]:
df

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   NaN
3      NaN  27.0   Hyd

In [54]:
df.fillna(method='ffill')

Names   Age  City
0   Ramesh   NaN  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0  Pune
3  Sathish  27.0   Hyd

In [56]:
df.fillna(method='backfill')


Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [58]:
df.fillna(method='bfill')


Names   Age  City
0   Ramesh  22.0  Pune
1   Suresh  22.0  Pune
2  Sathish  25.0   Hyd
3      NaN  27.0   Hyd

In [64]:
city_mode=df['City'].mode()
df['City'].fillna(city_mode)

0    Pune
1    Pune
2     NaN
3     Hyd
Name: City, dtype: object